rootProject.name = 'OpenDialer'

include(
        // core
        ":core:aosp",
        ":core:common",

        // data
        ":data:calls",
        ":data:callsCache",
        ":data:contacts",
        ":data:contactsSearch",

        // features
        ":feature:callDetail",
        ":feature:calls",
        ":feature:contacts",
        ":feature:contactsSearch",
        ":feature:inCall",
        ":feature:settings",

        // app
        ":app",
)